version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./frontend:/front-tesis
      - /front-tesis/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./backend:/back-tesis
      - /back-tesis/node_modules
